[package]
name = "human-repr"
version = "0.1.1"
edition = "2021"

authors = ["Rogério Sampaio de Almeida <rsalmei@gmail.com>"]
description = "Generate beautiful human representations of bytes, durations and even throughputs!"
keywords = ["format", "convert", "bytes", "duration", "throughput"]
repository = "https://github.com/rsalmei/human-repr.git"
readme = "README.md"
license = "MIT"

[dependencies]

[features]
1024 = []
iec = ["1024"]
nospace = []

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "counts"
harness = false
[[bench]]
name = "durations"
harness = false
[[bench]]
name = "throughputs"
harness = false
